source 'https://rubygems.org'

gem 'kramdown-parser-gfm'
gem 'jekyll-relative-links'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-include-cache'
gem 'jekyll-remote-theme'
gem 'wai-website-plugin'
